app-sre/er-aws-rds

.tool-versions, er_aws_rds/errors.py, er_aws_rds/input.py, tests/conftest.py, tests/test_input_validation.py, tests/test_module.py
Content:
- validating rds.logical_replication is applied via `pending-reboot` (see https://github.com/app-sre/qontract-reconcile/pull/4653)
- .tool-versions
- fixing some typos
=> APPSRE-10846 validate rds.logical_replication

er_aws_rds/rds.py
no special chars in password to fix error
```
CDKTF  Error: creating RDS DB Instance (xxx): InvalidParameterValue: The parameter MasterUserPassword is not a valid password. Only printable ASCII characters besides '/', '@', '"', ' ' may be used.
```
aws [doc](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html)
> Can include any printable ASCII character except "/", """, or "@". For RDS for Oracle, can't include the "&" (ampersand) or the "'" (single quotes) character.
=> fix(password): generate password with allowed special chars

er_aws_rds/rds.py
Rework random password config using https://github.com/app-sre/er-aws-rds/pull/5/commits/6093d5ca15a939271ad65bca20f5091560773fdc.
Some special chars are causing issues in application config, disable special chars to keep consistent with https://github.com/app-sre/qontract-reconcile/blob/c175f4df07fb7e42edaa58c886530186acfd9f6e/reconcile/utils/terrascript_aws_client.py#L2091-L2094
=> fix(password): generate password without special chars

Makefile, er_aws_rds/rds.py, tests/conftest.py, tests/test_module.py
[APPSRE-11439](https://issues.redhat.com/browse/APPSRE-11439)
Ensure same output regardless of restore from snapshot or not.
This pull request includes several changes to the `Makefile`, `er_aws_rds/rds.py`, `tests/conftest.py`, and `tests/test_module.py` files to improve functionality and add new features. The most important changes include creating a directory for generated files, modifying the `_outputs` method, updating the `input_data` and `input_object` functions, and adding a new test for outputs.
Improvements to the development environment:
* [`Makefile`](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R40): Added a command to create the `.gen` directory to ensure the necessary directory exists before running the `cdktf-provider-sync` command. …
=> fix: add user and password to output when restore from snapshot

.dockerignore, .gitignore, Makefile, cdktf.json, er_aws_rds/config.py, er_aws_rds/input.py, hooks/post_plan.py, hooks/pre_plan.py, pyproject.toml, tests/test_input_validation.py, tests/test_plan_validation.py
Bugfix and cleanup as https://github.com/app-sre/er-aws-rds/pull/80
Main bug is missing `parameter_group_name` in rds instance, so all new instances are using default parameter group.
Other small refactors:
* [`.dockerignore`](diffhunk://#diff-2f754321d62f08ba8392b9b168b83e24ea2852bb5d815d63e767f6c3d23c6ac5R7-R8): Added `module/plan` and `module/plan.json` to ignore list.
* [`Makefile`](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L7): Removed the `terraform fmt -check module/` command from the `format` target.
* [`er_aws_rds/config.py`](diffhunk://#diff-b49e08040940d41a552887fa6aad7408433b66cc813f76976204e187ef3b5a88R25-R28): Added a main entry point to call `generate_tf_files()` when the script is run directly.
* …
=> fix: populate parameter group name for rds instance

er_aws_rds/input.py, hooks/post_plan.py, module/main.tf
* `engine` must not be set when creating a read replica as is derived from the main instance. 
* The plan output when creating a read replica does not include the `engine` attribute. 
* We need to know the `engine` to validate the plan. 
Instead of relying on the plan to get the engine, now it's got from the variables. 
* `engine` is required in app-interface 
* now it's dropped in the terraform object instead of in the input data.
=> Fix plan validation for read replicas

Dockerfile
Forgot to bump image version in https://github.com/app-sre/er-aws-rds/pull/102
=> chore: bump image version to 0.6.0

Dockerfile
forgot to bump base version https://github.com/app-sre/er-base-terraform/pull/20 in https://github.com/app-sre/er-aws-rds/pull/102
=> chore: bump er-base-terraform-main to 0.3.4

Dockerfile, er_aws_rds/input.py, module/basic_instance.tftest.hcl, module/main.tf, pyproject.toml, tests/test_input_validation.py, uv.lock
Drop support for `blue_green_update`, use `blue_green_deployment` instead.
[APPSRE-11434](https://issues.redhat.com/browse/APPSRE-11434)
This pull request includes several changes to various files, primarily focusing on updating labels and version numbers, modifying type hints in the `er_aws_rds/input.py` file, and removing the `blue_green_update` feature. Additionally, a new test has been added to validate the removal of `blue_green_update`.
* [`Dockerfile`](diffhunk://#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L3-R3): Updated `konflux.additional-tags` label from "0.6.1" to "0.6.2".
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L3-R3): Updated project version from "0.6.1" to "0.6.2".
* …
=> Drop support for blue_green_update

Dockerfile, er_aws_rds/input.py, hooks/pre_run.py, hooks/utils/blue_green_deployment_manager.py, hooks/utils/blue_green_deployment_model.py, hooks/utils/models.py, pyproject.toml, tests/conftest.py, tests/test_blue_green_deployment_manager.py, tests/test_input_validation.py, tests/test_pre_run.py, uv.lock
If the instance is a replica, then validate:
* no `parameter_group` specified, because blue/green deployment only support one, replica shouldn't set parameter group, not set means to use source instance by AWS
* `deletion_protection` should be disabled, because blue/green deployment need to delete instance
Also skip terraform steps if source has `blue_green_deployment` enabled to avoid conflicts.
Need to promote same time as https://github.com/app-sre/qontract-reconcile/pull/4913
[APPSRE-11434](https://issues.redhat.com/browse/APPSRE-11434)
=> Support blue/green deployment for replicas

Dockerfile, er_aws_rds/input.py, pyproject.toml, tests/test_input_terraform.py, tests/test_input_validation.py, uv.lock
`old_parameter_group` is no longer needed
[APPSRE-11657](https://issues.redhat.com/browse/APPSRE-11657)
=> Deprecate old parameter group

Dockerfile, er_aws_rds/errors.py, er_aws_rds/input.py, hooks/post_plan.py, hooks/utils/aws_api.py, pyproject.toml, tests/conftest.py, tests/test_aws_api.py, tests/test_blue_green_deployment_manager.py, tests/test_input_validation.py, tests/test_plan_validation.py, uv.lock
* `apply_method` change only will cause reconcile loop, detect it early on both create and update to prevent the loop described in https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_parameter_group#problematic-plan-changes
* `apply_method` can't be `immediate` on `static` parameters such as `rds.logical_replication`, use this generic validation to cover old hard coded check.
* use boto3 paginator in aws api methods to avoid partial paginated response
[APPSRE-11695](https://issues.redhat.com/browse/APPSRE-11695)
* Removed the `RDSLogicalReplicationError` custom exception and the corresponding validation logic in `er_aws_rds/input.py`. [[1]](diffhunk://#diff-2ebfa68843ed03c75bcb199cb18ebadd895d7801ba50764b7081ae0c37995af1L1-L2) …
=> Validate parameter group changes

hooks/post_plan.py, tests/test_plan_validation.py
Throw error when unset `parameter_group` since terraform will ignore it, and it will fail during parameter group deletion as RDS instance is still using it.
[APPSRE-11722](https://issues.redhat.com/browse/APPSRE-11722)
* Added `_filter_by_actions` and `_filter_by_type` static methods to filter resource changes by actions and type, respectively. These methods improve code reuse and readability.
* Updated existing property methods (`resource_updates`, `resource_deletions`, `resource_creations`, `aws_db_instance_creations`, `aws_db_instance_updates`, `aws_db_instance_deletions`) to use the new filtering utility methods.
* Added new properties `aws_db_instances` and `aws_db_parameter_groups` to filter resource changes by specific AWS resource types.
* Introduced …
=> Parameter group deletion validation

er_aws_rds/input.py, tests/test_input_validation.py
Validate cross region read replicas according to https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/blue-green-deployments-considerations.html
> Cross-region read replicas are not currently supported for Blue Green Deployments
[APPSRE-11707](https://issues.redhat.com/browse/APPSRE-11707)
Validation logic improvements:
* [`er_aws_rds/input.py`](diffhunk://#diff-fa4b05ce58b400425e2e210a5d5965854fe8c2eeb2490152b8e3774a25f1e7e8R347-R350): Added a check to ensure that cross-region read replicas are not supported for blue-green deployments and raise a `ValueError` if this condition is met.
Testing enhancements:
* [`tests/test_input_validation.py`](diffhunk://#diff-08fc3d02ead45670ed98689a721d71d5e8135f5bdf27a1bc64f3800944694c81R298-R318): Added a new test case …
=> feat: validate cross-region read replicas for blue_green_deployment

Dockerfile, er_aws_rds/input.py, hooks/utils/blue_green_deployment_manager.py, pyproject.toml, tests/test_blue_green_deployment_manager.py, tests/test_input_validation.py, uv.lock
Validate read replica config (`engine_version`) is matching replica source instance after blue/green deployment done, so terraform can just refresh to sync state.
[APPSRE-11714](https://issues.redhat.com/browse/APPSRE-11714)
* [`er_aws_rds/input.py`](diffhunk://#diff-fa4b05ce58b400425e2e210a5d5965854fe8c2eeb2490152b8e3774a25f1e7e8L68-L75): Restructured the `ReplicaSource` class to include a `blue_green_deployment` attribute instead of `blue_green_deployment_enabled`, and added validation logic to ensure configurations match the requirements for blue-green deployments. [[1]](diffhunk://#diff-fa4b05ce58b400425e2e210a5d5965854fe8c2eeb2490152b8e3774a25f1e7e8L68-L75) [[2]](diffhunk://#diff-fa4b05ce58b400425e2e210a5d5965854fe8c2eeb2490152b8e3774a25f1e7e8R90-R97) …
=> Validate read replica has matching desired config as replica source instance

hooks/utils/aws_api.py, tests/test_aws_api.py
Fix parameter group check introduced in https://github.com/app-sre/er-aws-rds/pull/135
`rds_client.describe_db_parameter_groups` will throw exception instead of return empty list.
[APPSRE-11722](https://issues.redhat.com/browse/APPSRE-11722)
=> fix: handle parameter group not found error

.env.example, Dockerfile, hooks/post_plan.py, hooks/post_run.py, hooks/pre_run.py, hooks/utils/blue_green_deployment_manager.py, hooks/utils/blue_green_deployment_model.py, hooks/utils/models.py, hooks/utils/runtime.py, pyproject.toml, tests/test_blue_green_deployment_manager.py, tests/test_blue_green_deployment_model.py, tests/test_plan_validation.py, tests/test_post_run.py, tests/test_pre_run.py, tests/test_runtime.py, uv.lock
[APPSRE-11434](https://issues.redhat.com/browse/APPSRE-11434)
When there are changes required for blue/green deployment, but can be done via terraform, pre_run hook will mark it as rerun, then post_run hook will exit as error to rerun after terraform flow.
Supported pending prepares are:
* deletion_protection
* backup_retention_period
* target parameter_group
This will allow prepare and create blue/green deployment in one change, note `delete` has to be `False` otherwise terraform will try to apply other changes should be done in blue/green deployment, post_plan validation will catch that.
* [`hooks/post_plan.py`](diffhunk://#diff-e1e101fc08c044624f7b3896a524c3e118c82887f9fa2f4e88b6b3c2c58959d6R178): Added a condition to check for the `delete` attribute in Blue/Green Deployment and …
=> feat: support pending prepares to be applied in blue/green deployment

module/main.tf
Fix aws_kms_key count logic to use var.rds_instance.kms_key_id. 
Ensure the KMS key is resolved in the replica’s region (not replica_source).
=> fix kms_key_id usage

Dockerfile, er_aws_rds/input.py, module/providers.tf, module/variables.tf, pyproject.toml, tests/conftest.py, uv.lock
Config provider to use tags as default_tags, ensure all resources created contain same tags.
Depends on https://github.com/app-sre/qontract-reconcile/pull/5220
[APPSRE-12469](https://issues.redhat.com/browse/APPSRE-12469)
=> Use tags as provider default_tags

Dockerfile, hooks/pre_run.py, pyproject.toml, tests/test_post_run.py, tests/test_pre_run.py, uv.lock
`ValidationError` message is used in pipeline check output, skip stack trace to make it easier to read.
**Error handling improvements:**
* Added explicit handling for `pydantic.ValidationError` in the `main` function of `hooks/pre_run.py`, logging the error and exiting with an error code. [[1]](diffhunk://#diff-cf709ac2096dbe6c98a19716b4cba5eaa840aa655cb38df6ece115609e822544R7) [[2]](diffhunk://#diff-cf709ac2096dbe6c98a19716b4cba5eaa840aa655cb38df6ece115609e822544R31-R33)
**Unit test enhancements:**
* Added a test case to `tests/test_pre_run.py` that simulates a `ValidationError` during deployment management, verifying correct logging and exit code.
* Updated existing tests in `tests/test_pre_run.py` and `tests/test_post_run.py` to patch logging and assert that appropriate log messages …
=> refactor: log ValidationError without stack trace
